{{- if .Values.slave.enabled }}
# Defines the deployment for the Alfresco Search (Solr) App
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "alfresco-search.fullName" . }}-solr-slave
  labels:
    app: {{ template "alfresco-search.fullName" . }}-solr-slave
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: search-slave
spec:
  replicas: {{ .Values.slave.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "alfresco-search.fullName" . }}-solr-slave
        release: {{ .Release.Name }}
    spec:
#    {{- with .Values.affinity }}
#      affinity:
#{{ tpl . $ | indent 8 }}
#    {{- end }}
#    {{- with .Values.tolerations }}
#      tolerations:
#{{ toYaml . | indent 8 }}
#    {{- end }}
      {{- if .Values.common.registryPullSecrets }}
      # only set this secret if a private docker registry variable is defined
      imagePullSecrets:
        - name: {{ .Values.common.registryPullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "alfresco-search-slave.dockerImage" . }}
          imagePullPolicy: {{ template "alfresco-search.pullPolicy" . }}
          envFrom:
          - configMapRef:
              name: {{ template "alfresco-search.fullName" . }}-solr-slave-configmap
          ports:
            - containerPort: {{ template "alfresco-search.internalPort" . }}
          resources:
{{ toYaml .Values.common.resources | indent 12 }}
          volumeMounts:
          - name: data
            mountPath: {{ .Values.common.persistence.search.data.mountPath }}
            subPath: {{ .Values.slave.persistence.search.data.subPath }}
          readinessProbe:
            httpGet:
              path: /solr-slave
              port: {{ template "alfresco-search.internalPort" . }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /solr/alfresco/admin/ping
              port: {{ template "alfresco-search.internalPort" . }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: 1
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
      initContainers:
        - name: init-db
          image: busybox
          # command to allow solr to write to EFS volume. Details: https://issues.alfresco.com/jira/browse/DEPLOY-419
          command: ["sh", "-c", "chown -R 33007:33007 {{ .Values.common.persistence.search.data.mountPath }}"]
          volumeMounts:
          - name: data
            mountPath: {{ .Values.common.persistence.search.data.mountPath }}
            subPath: {{ .Values.slave.persistence.search.data.subPath }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "{{ .Values.slave.persistence.existingClaim | default (printf "%s-solr-slave-claim" (include "alfresco-search.fullName" .)) }}"
{{- end }}