kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "alfresco-search.fullName" . }}-solr-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi