name: alfresco-search
version: 0.0.2
description: A Helm chart for deploying Alfresco Search
keywords:
- search
- search services
- alfresco search services
- insight
- insight engine
- alfresco insight engine
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4