# Default values for alfresco-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Define the alfresco-search properties to use in the k8s cluster
# This is the search provider used by alfresco-content-repository
common: &commonConfig
  replicaCount: 1
  # Define the type of Alfresco Search to use. The default is Alfresco Search Services.
  # The type can be set to use Insight Engine with --set alfresco-search.type="insight-engine",alfresco-search.registryPullSecrets="quay-registry-secret",alfresco-insight-zeppelin.enabled="true"
  # As the Docker Image for Insight Engine is not publicly available the registryPullSecrets has to be set
  # More information can be found on https://github.com/Alfresco/alfresco-anaxes-shipyard/blob/master/SECRETS.md
  type: "search-services"
  searchServicesImage:
    repository: alfresco/alfresco-search-services
    tag: "latest"
    pullPolicy: &searchDockerImagePullPolicy Always
    internalPort: &searchDockerImageInternalPort 8983
  insightEngineImage:
    repository: quay.io/alfresco/insight-engine
    tag: "latest"
    pullPolicy: *searchDockerImagePullPolicy
    internalPort: *searchDockerImageInternalPort
  service: &serviceConfig
    name: solr
    type: ClusterIP
  ingress:
    enabled: true
    path: /solr
    # Default solr basic auth user/password: admin / admin
    # You can create your own with htpasswd utilility & encode it with base640.
    # Example: `echo -n "$(htpasswd -nbm admin admin)" | base64` # i.e. admin / admin
    # basicAuth: YWRtaW46JGFwcjEkVVJqb29uS00kSEMuS1EwVkRScFpwSHB2a3JwTDd1Lg==
    basicAuth:
    # Comma separated list of IP CIDR to limit search endpoint over the internet
    whitelist_ips: "0.0.0.0/0"
  # The parent chart will set the values for "repository.host" and "repository.port"
  repository: {}
  environment: &environmentConfig
    SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    SOLR_OPTS: "-Dsolr.content.dir=/opt/alfresco-search-services/data/contentstore"
  resources:
    requests:
      memory: "250Mi"
    limits:
      memory: "1024Mi"
  # Defines the mounting points for the persistence required by the apps in the cluster
  # the solr data folder containing the indexes for the alfresco-search-services is mapped to alfresco-content-services/solr-data
  persistence: &persistenceConfig
    existingClaim: "alfresco-volume-claim"
    search:
      data:
        mountPath: "/opt/alfresco-search-services/data"
  alfresco-insight-zeppelin:
    enabled: false

master:
  <<: *commonConfig
  service:
    <<: *serviceConfig
    externalPort: &searchExternalPort 80
  environment:
    <<: *environmentConfig
    REPLICATION_TYPE: master
    REPLICATION_AFTER: commit,startup
    REPLICATION_CONFIG_FILES: schema.xml,stopwords.txt
  persistence:
    <<: *persistenceConfig
    search:
      data:
        subPath: "alfresco-content-services/solr-data"

slave:
  enabled: false
  <<: *commonConfig
  service:
    <<: *serviceConfig
    externalPort: 81
  environment:
    <<: *environmentConfig
    REPLICATION_TYPE: slave
    REPLICATION_MASTER_PORT: *searchExternalPort
    REPLICATION_MASTER_PROTOCOL: http
    REPLICATION_CORE_NAME: alfresco
    REPLICATION_POLL_INTERVAL: 00:00:60
  persistence:
    <<: *persistenceConfig
    search:
      data:
        subPath: "alfresco-content-services/solr-data-slave"