# Default values for alfresco-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Define the alfresco-search properties to use in the k8s cluster
# This is the search provider used by alfresco-content-repository
replicaCount: 1
# Define the type of Alfresco Search to use. The default is Alfresco Search Services.
# The type can be set to use Insight Engine with --set alfresco-services-services.type="insight-engine",registryPullSecrets="quay-registry-secret"
# As the Docker Image for Insight Engine is not publicly available the registryPullSecrets has to be set
# More information can be found on https://github.com/Alfresco/alfresco-anaxes-shipyard/blob/master/SECRETS.md
type: "search-services"
searchServicesImage:
  repository: alfresco/alfresco-search-services
  tag: "1.1.1"
  pullPolicy: &searchDockerImagePullPolicy Always
  internalPort: &searchDockerImageInternalPort 8983
insightEngineImage:
  repository: quay.io/alfresco/insight-engine
  tag: "1.0.0-SNAPSHOT"
  pullPolicy: *searchDockerImagePullPolicy
  internalPort: *searchDockerImageInternalPort
service:
  name: solr
  type: ClusterIP
  externalPort: 80
ingress:
  path: /solr
# The parent chart will set the values for "repository.host" and "repository.port"
repository: {}
environment:
  SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
  SOLR_OPTS: "-Dsolr.content.dir=/opt/alfresco-search/data/contentstore"
resources:
  requests:
    memory: "250Mi"
  limits:
    memory: "1024Mi"
# Defines the mounting points for the persistence required by the apps in the cluster
# the solr data folder containing the indexes for the alfresco-search is mapped to alfresco-content/solr-data
persistence:
  existingClaim: "alfresco-volume-claim"
  search:
    data:
      mountPath: "/opt/alfresco-search/data"
      subPath: "alfresco-content-services/solr-data"